export const ERROR_CODES = {
  AUTH: {
    UNAUTHORIZED: "UNAUTHORIZED",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
    INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
    INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
    SESSION_EXPIRED: "SESSION_EXPIRED",
    SESSION_INVALID: "SESSION_INVALID",
  },

  GENERAL: {
    VALIDATION_ERROR: "VALIDATION_ERROR",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  },
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];