export const ERROR_CODES = {
  AUTH_401: "UNAUTHORIZED_ERROR",
  AUTH_002: "INVALID_CREDENTIALS",
  AUTH_403: "FORBIDDEN_ERROR",
  AUTH_404: "NOT_FOUND_ERROR",
  AUTH_CONFLICT: "CONFLICT_ERROR",
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];