export const ERROR_CODES = {
  AUTH: {
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    ACCOUNT_NOT_VERIFIED: "ACCOUNT_NOT_VERIFIED",

    ACCESS_TOKEN_MISSING: "ACCESS_TOKEN_MISSING",
    ACCESS_TOKEN_EXPIRED: "ACCESS_TOKEN_EXPIRED",
    INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",

    REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
    INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
    REFRESH_TOKEN_MISSING: "REFRESH_TOKEN_MISSING",

    SESSION_EXPIRED: "SESSION_EXPIRED",
    SESSION_INVALID: "SESSION_INVALID",
    SESSION_CONFLICT: "SESSION_CONFLICT",

    UNAUTHORIZED: "UNAUTHORIZED",
    INVALID_USER: "INVALID_USER",

    INVALID_GOOGLE_TOKEN: "INVALID_GOOGLE_TOKEN",
  },

  GENERAL: {
    BAD_REQUEST: "BAD_REQUEST",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT",
    UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",
    TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
  },

  USER: {
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  },
} as const;