export const TYPES = {
  Redis: Symbol.for("Redis"),
  
  ILogger: Symbol.for("ILogger"),

  IUserRepository: Symbol.for("IUserRepository"),
  IOTPRepository: Symbol.for("IOTPRepository"),
  IPendingUserRepository: Symbol.for("IPendingUserRepository"),
  ILeadRepository: Symbol.for("ILeadRepository"),
  IDesignerRepository: Symbol.for("IDesignerRepository"),
  IDeliverableRepository: Symbol.for("IDeliverableRepository"),

  IPasswordService: Symbol.for("IPasswordService"),
  IOtpService: Symbol.for("IOtpService"),
  IPendingUserService: Symbol.for("IPendingUserService"),
  IEmailService: Symbol.for("IEmailService"),
  ITokenService: Symbol.for("ITokenService"),
  ISessionService: Symbol.for("ISessionService"),
  IGoogleAuthService: Symbol.for("IGoogleAuthService"),

  IRegisterUserUseCase: Symbol.for("IRegisterUserUseCase"),
  IVerifyOtpUseCase: Symbol.for("IVerifyOtpUseCase"),
  IResendOtpUseCase: Symbol.for("IResendOtpUseCase"),
  IRefreshTokenUseCase: Symbol.for("IRefreshTokenUseCase"),
  ILogoutUseCase: Symbol.for("ILogoutUseCase"),
  ILogoutAllDevicesUseCase: Symbol.for("ILogoutAllDevicesUseCase"),
  ILoginUseCase : Symbol.for("ILoginUseCase"),
  IGetMeUseCase: Symbol.for("IGetMeUseCase"),
  IForgotPasswordUseCase: Symbol.for("IForgotPasswordUseCase"),
  IVerifyResetOtpUseCase: Symbol.for("IVerifyResetOtpUseCase"),
  IResetPasswordUseCase: Symbol.for("IResetPasswordUseCase"),
  IResendForgotPasswordOtpUseCase: Symbol.for("IResendForgotPasswordOtpUseCase"),
  IGoogleAuthUseCase: Symbol.for("IGoogleAuthUseCase"),
  IVerifyEmailUseCase: Symbol.for("IVerifyEmailUseCase"),

  ICreateLeadUseCase: Symbol.for("ICreateLeadUseCase"),
  IGetAllLeadsUseCase: Symbol.for("IGetAllLeadsUseCase"),
  IAssignDesignerUseCase: Symbol.for("IAssignDesignerUseCase"),
  IGetDesignerOptionsUseCase: Symbol.for("IGetDesignerOptionsUseCase"),
  ICreateManualLeadUseCase: Symbol.for("ICreateManualLeadUseCase"),
  IDeleteLeadUseCase: Symbol.for("IDeleteLeadUseCase"),
  IUpdateLeadUseCase: Symbol.for("IUpdateLeadUseCase"),
  
  IGetAllDesignerUseCase: Symbol.for("IGetAllDesignerUseCase"),
  ICreateDesignerUseCase: Symbol.for("ICreateDesignerUseCase"),
  IUpdateDesignerUseCase: Symbol.for("IUpdateDesignerUseCase"),
  IToggleDesignerBlockUseCase: Symbol.for("IToggleDesignerBlockUseCase"),
  IDeleteDesignerUseCase: Symbol.for("IDeleteDesignerUseCase"),
  
  IGetAllDeliverablesUseCase: Symbol.for("IGetAllDeliverablesUseCase"),

  AuthController: Symbol.for("AuthController"),
  LeadController: Symbol.for("LeadController"),
  DesignerController: Symbol.for("DesignerController"),
  DeliverableController: Symbol.for("DeliverableController"),
};